# Generated by Django 4.1.1 on 2022-10-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_subcategory_product_categoryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryId',
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory'),
        ),
    ]
