# Generated by Django 4.1.1 on 2022-10-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_isboolean'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagess', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='isBoolean',
            field=models.BooleanField(default=True, verbose_name='В наличие'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(to='shop.imagemodel'),
        ),
    ]
