# Generated by Django 4.1.1 on 2022-10-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
