# Generated by Django 4.1.1 on 2022-10-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_image_delete_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='a',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
