# Generated by Django 4.1.1 on 2022-10-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='a',
        ),
    ]
