# Generated by Django 4.1.1 on 2022-12-02 10:09

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_user_delete_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='order',
            name='user_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
