# Generated by Django 4.1.1 on 2022-12-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_user_id_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='_id',
            new_name='id',
        ),
    ]
